[project]
name = "diligentservices-quarto"
version = "0.1.0"
description = "Metal-Roof-Rib-Joist-Calculations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "plotly>=5.24.1",
]
